#!/usr/bin/env python3

# Phase 0 guardrail for the platform-abstraction plan
# (docs/platform-abstraction/plan.md, phase0-cpp-classification.md).
#
# Reports host-OS / host-arch CPP conditionals (`*_HOST_OS`, `*_HOST_ARCH`) in
# compiler/ that live OUTSIDE the host-abstraction layer and are not in the
# baseline allowlist of files that already contain such conditionals.
#
# Why only compiler/ : there `*_HOST_*` describes the machine ghc *runs on*
# (the host) and should be delegated to GHC.Platform.Host. In libraries/ the
# same macros describe the *target* the library is compiled for and stay as
# per-OS module selection, so they are deliberately not flagged here.
#
# Lifecycle:
#   * Phase 0 (now): ENFORCE = False -> warn-only. Findings are printed but the
#     linter exits 0, so it never breaks CI. With ALLOWLIST seeded to today's
#     offenders, a clean tree produces no output; only NEW host CPP in other
#     compiler files is reported.
#   * Phase 2: as each file is converted to GHC.Platform.Host, remove it from
#     ALLOWLIST so the linter guards it against regressions.
#   * Phase 6: set ENFORCE = True to make violations fail CI.

import re
from pathlib import Path

from linter import run_linters, Linter, Warning, lint_failure

# Phase 0: warn-only. Flip to True in Phase 6 to make this a hard CI gate.
ENFORCE = False

# CPP identifiers that denote the host OS / architecture.
HOST_MACRO_RE = re.compile(r'\b\w+_HOST_(?:OS|ARCH)\b')
COND_RE = re.compile(r'^\s*#\s*(?:if|ifdef|ifndef|elif)\b')

# The host-abstraction layer: the one place host CPP is allowed to live.
ABSTRACTION_LAYER_PREFIX = 'compiler/GHC/Platform/Host'

# Baseline: compiler files that already contain host-OS/arch CPP as of Phase 0.
# Remove entries here as they are converted (plan Phase 2). Generated by
# docs/platform-abstraction/census.py.
ALLOWLIST = {
    'compiler/GHC.hs',
    'compiler/GHC/Driver/MakeAction.hs',
    'compiler/GHC/Driver/Session.hs',
    'compiler/GHC/Linker/Loader.hs',
    'compiler/GHC/Llvm/Types.hs',
    'compiler/GHC/Runtime/Interpreter/Init.hs',
    'compiler/GHC/Runtime/Interpreter/Wasm.hs',
    'compiler/GHC/Runtime/Utils.hs',
    'compiler/GHC/SysTools/BaseDir.hs',
    'compiler/GHC/Utils/Constants.hs',
    'compiler/GHC/Utils/Panic.hs',
}

MESSAGE = (
    'host-OS/arch CPP (`*_HOST_OS`/`*_HOST_ARCH`) should be delegated to the '
    'GHC.Platform.Host abstraction (docs/platform-abstraction/plan.md) rather '
    'than branched on inline in compiler/.'
)


def in_compiler(path: Path) -> bool:
    return len(path.parts) > 0 and path.parts[0] == 'compiler'


class HostCppLinter(Linter):
    def __init__(self):
        Linter.__init__(self)
        self.add_path_filter(in_compiler)
        self.add_path_filter(lambda p: p.suffix in ('.hs', '.hsc'))
        self.add_path_filter(lambda p: p.as_posix() not in ALLOWLIST)
        self.add_path_filter(
            lambda p: not p.as_posix().startswith(ABSTRACTION_LAYER_PREFIX))

    def lint(self, path: Path):
        if not path.is_file():
            return
        try:
            lines = path.read_text().split('\n')
        except UnicodeDecodeError:
            return
        for line_no, line in enumerate(lines, start=1):
            if COND_RE.match(line) and HOST_MACRO_RE.search(line):
                w = Warning(path=path, line_no=line_no,
                            line_content=line, message=MESSAGE)
                if ENFORCE:
                    self.add_warning(w)
                else:
                    # Warn-only: report but do not fail CI.
                    lint_failure(w.path, w.line_no, w.line_content,
                                 '[warn-only] ' + w.message)


if __name__ == '__main__':
    # In warn-only mode no Warnings are registered, so run_linters exits 0.
    run_linters([HostCppLinter()])
